In [ ]:
#Import some basic libraries
import numpy as np # The NumPy library provides support for efficient numerical computing in Python
import pandas as pd # The Pandas library provides high-performance data manipulation and analysis tools

In [ ]:
# The URL of the file on Google Drive, this file is rainfall.csv
url='https://drive.google.com/file/d/1pyG3_AtNnnaMrDA_eOA0A0d1yoOcNwAX/view?usp=share_link'
# Extracting the file ID from the URL
file_id=url.split('/')[-2]
# Constructing the download URL using the file ID
dwn_url='https://drive.google.com/uc?id=' + file_id
# Loading the data from the download URL into a Pandas DataFrame
data = pd.read_csv(dwn_url)
print(data.head()) # Printing the first few rows of the DataFrame

                 SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5   
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1   
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9   
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1   
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7   

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3   
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3   
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1   
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9   
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7   

   Jun-Sep  Oct-Dec  
0   1696.3    980.3  
1   2185.9    716.7  
2   1874.0    690.6  
3   

In [ ]:
# Filling missing values in the each column with the mean value of the column
data['JAN'].fillna((data['JAN'].mean()), inplace=True)
data['FEB'].fillna((data['FEB'].mean()), inplace=True)
data['MAR'].fillna((data['MAR'].mean()), inplace=True)
data['APR'].fillna((data['APR'].mean()), inplace=True)
data['MAY'].fillna((data['MAY'].mean()), inplace=True)
data['JUN'].fillna((data['JUN'].mean()), inplace=True)
data['JUL'].fillna((data['JUL'].mean()), inplace=True)
data['AUG'].fillna((data['AUG'].mean()), inplace=True)
data['SEP'].fillna((data['SEP'].mean()), inplace=True)
data['OCT'].fillna((data['OCT'].mean()), inplace=True)
data['NOV'].fillna((data['NOV'].mean()), inplace=True)
data['DEC'].fillna((data['DEC'].mean()), inplace=True)
data['ANNUAL'].fillna((data['ANNUAL'].mean()), inplace=True)
data['Jan-Feb'].fillna((data['Jan-Feb'].mean()), inplace=True)
data['Mar-May'].fillna((data['Mar-May'].mean()), inplace=True)
data['Jun-Sep'].fillna((data['Jun-Sep'].mean()), inplace=True)
data['Oct-Dec'].fillna((data['Oct-Dec'].mean()), inplace=True)

In [ ]:
print(data.head())

                 SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5   
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1   
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9   
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1   
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7   

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3   
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3   
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1   
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9   
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7   

   Jun-Sep  Oct-Dec  
0   1696.3    980.3  
1   2185.9    716.7  
2   1874.0    690.6  
3   

In [ ]:
data=np.array(data) # Converting the DataFrame to a NumPy array
print(data.shape) # Printing the shape of the NumPy array


(4116, 19)


In [ ]:
state = {name:i for i, name in enumerate(sorted(set(data[:,0])))} # Sorting the unique values in the first column of the 'data' array and assigning them indices
print(state) # Printing the resulting dictionary

{'ANDAMAN & NICOBAR ISLANDS': 0, 'ARUNACHAL PRADESH': 1, 'ASSAM & MEGHALAYA': 2, 'BIHAR': 3, 'CHHATTISGARH': 4, 'COASTAL ANDHRA PRADESH': 5, 'COASTAL KARNATAKA': 6, 'EAST MADHYA PRADESH': 7, 'EAST RAJASTHAN': 8, 'EAST UTTAR PRADESH': 9, 'GANGETIC WEST BENGAL': 10, 'GUJARAT REGION': 11, 'HARYANA DELHI & CHANDIGARH': 12, 'HIMACHAL PRADESH': 13, 'JAMMU & KASHMIR': 14, 'JHARKHAND': 15, 'KERALA': 16, 'KONKAN & GOA': 17, 'LAKSHADWEEP': 18, 'MADHYA MAHARASHTRA': 19, 'MATATHWADA': 20, 'NAGA MANI MIZO TRIPURA': 21, 'NORTH INTERIOR KARNATAKA': 22, 'ORISSA': 23, 'PUNJAB': 24, 'RAYALSEEMA': 25, 'SAURASHTRA & KUTCH': 26, 'SOUTH INTERIOR KARNATAKA': 27, 'SUB HIMALAYAN WEST BENGAL & SIKKIM': 28, 'TAMIL NADU': 29, 'TELANGANA': 30, 'UTTARAKHAND': 31, 'VIDARBHA': 32, 'WEST MADHYA PRADESH': 33, 'WEST RAJASTHAN': 34, 'WEST UTTAR PRADESH': 35}


In [ ]:
df=pd.DataFrame(data[:,:14]).replace(state) # Creating a DataFrame from the first 14 columns of the 'data' array

In [ ]:
df.to_csv("data.csv") # Exporting the DataFrame 'df' to a CSV file named 'data.csv'

In [ ]:
print(df.head()) # Printing the first few rows of the DataFrame using the 'head()' function

   0     1     2      3     4      5      6      7      8      9      10  \
0   0  1901  49.2   87.1  29.2    2.3  528.8  517.5  365.1  481.1  332.6   
1   0  1902   0.0  159.8  12.2    0.0  446.1  537.1  228.9  753.7  666.2   
2   0  1903  12.7  144.0   0.0    1.0  235.1  479.9  728.4  326.7  339.0   
3   0  1904   9.4   14.7   0.0  202.4  304.5  495.1  502.0  160.1  820.4   
4   0  1905   1.3    0.0   3.3   26.9  279.5  628.7  368.7  330.5  297.0   

      11     12     13  
0  388.5  558.2   33.6  
1  197.2  359.0  160.5  
2  181.2  284.4  225.0  
3  222.2  308.7   40.1  
4  260.7   25.4  344.7  


In [ ]:
data2=np.array(df) # Converting the DataFrame 'df' to a NumPy array

In [ ]:
print(data2.shape) # Printing the shape of the array

(4116, 14)


In [ ]:
print(data2[:200]) # Accessing the first 200 rows of the NumPy array 'data2' using slicing

[[0.000e+00 1.901e+03 4.920e+01 ... 3.885e+02 5.582e+02 3.360e+01]
 [0.000e+00 1.902e+03 0.000e+00 ... 1.972e+02 3.590e+02 1.605e+02]
 [0.000e+00 1.903e+03 1.270e+01 ... 1.812e+02 2.844e+02 2.250e+02]
 ...
 [1.000e+00 2.006e+03 6.000e+00 ... 7.720e+01 6.970e+01 2.170e+01]
 [1.000e+00 2.007e+03 1.340e+01 ... 1.026e+02 2.430e+01 6.900e+00]
 [1.000e+00 2.008e+03 7.670e+01 ... 1.151e+02 1.700e+00 2.600e+00]]


In [ ]:
x=[] # Creating an empty list 'x' to store data points along the x-axis
y=[] # Creating an empty list 'y' to store data points along the y-axis

In [ ]:
count=0 # Setting the initial count to 0
flood_min=254 # Defining the minimum flood value as 254

In [ ]:
# Looping through a range of values from 0 to 35
for i in range(36):
    # Printing the data in the first column of 'data2' and the current value of 'i'
    print(data2[:,0],i)
    # Filtering the data based on the current value of 'i' and selecting columns 2 onwards
    temp=data2[data2[:,0]==i][:,2:].flatten()
    temp=np.array(temp)
    # Iterating through each value in 'temp' and appending it to the list 'x'
    for j in range(temp.shape[0]):
        x.append([i,temp[j]])
    # Printing the values in 'temp'
    print(temp)
    # Iterating through each value in 'temp' and assigning a corresponding value to 'y' based on certain conditions
    for j in range(temp.shape[0]):
        # Generating random noise
        noise=25*np.random.normal(0,0.45)
        # Assigning a label of 3 if the value is greater than or equal to 354 + noise
        if(temp[j]>=354+noise):
            y.append(3)
        # Assigning a label of 1 if the value is greater than 204 - abs(noise) and less than or equal to 254
        elif(temp[j]>204-abs(noise) and temp[j] <=254):
            y.append(1)
        # Assigning a label of 2 if the value is greater than 254 and less than 354 + noise
        elif(temp[j]>254 and temp[j]<354+noise):
            y.append(2)
        else:
            y.append(0) #assigning a label 0 for all other values

[ 0.  0.  0. ... 18. 18. 18.] 0
[ 49.2  87.1  29.2 ... 252.1 236.3 129.9]
[ 0.  0.  0. ... 18. 18. 18.] 1
[48.1 69.8 71.1 ... 65.2 33.8 29.8]
[ 0.  0.  0. ... 18. 18. 18.] 2
[27.1 19.5 30.6 ... 62.6 14.  15.2]
[ 0.  0.  0. ... 18. 18. 18.] 3
[51.8 19.6 11.9 ... 10.4  0.   0. ]
[ 0.  0.  0. ... 18. 18. 18.] 4
[ 48.9 116.5  27.8 ...  17.7   0.6   1.5]
[ 0.  0.  0. ... 18. 18. 18.] 5
[18.8 80.9  7.2 ... 59.7 81.2  2. ]
[ 0.  0.  0. ... 18. 18. 18.] 6
[  1.8   0.6  10.7 ... 208.5 124.2  14.3]
[ 0.  0.  0. ... 18. 18. 18.] 7
[48.5 38.1 15.7 ... 38.2  1.2  0.9]
[ 0.  0.  0. ... 18. 18. 18.] 8
[21.6  8.9  2.9 ...  5.   0.5  0.8]
[ 0.  0.  0. ... 18. 18. 18.] 9
[62.6 31.3  8.2 ... 11.8  0.5  4.9]
[ 0.  0.  0. ... 18. 18. 18.] 10
[37.1 58.4  3.9 ... 32.7  2.3  6.3]
[ 0.  0.  0. ... 18. 18. 18.] 11
[4.2 0.  0.6 ... 2.2 0.3 0. ]
[ 0.  0.  0. ... 18. 18. 18.] 12
[35.4 28.9 11.1 ...  3.7  2.3  0.2]
[ 0.  0.  0. ... 18. 18. 18.] 13
[137.8 174.5  75.  ...  17.7  14.5  25. ]
[ 0.  0.  0. ... 18. 18. 1

In [ ]:
# Converting 'x' and 'y' to NumPy arrays
x=np.array(x)
y=np.array(y)
y=y.reshape((y.shape[0],1)) # Reshaping 'y' to have a shape of (number of samples, 1)
data_final=np.concatenate((y,x),axis=1) # Concatenating 'y' and 'x' arrays along axis 1
df2=pd.DataFrame(data_final) # Creating a DataFrame 'df2' from 'data_final'
df2.to_csv("final_data.csv") # Saving 'df2' as a CSV file named 'final_data.csv'

In [ ]:
df2.head() #printing the first few rows of df2

0    1      2
0  0.0  0.0   49.2
1  0.0  0.0   87.1
2  0.0  0.0   29.2
3  0.0  0.0    2.3
4  3.0  0.0  528.8

In [ ]:
from google.colab import files # Importing the necessary library
files.download('final_data.csv') # Using the files.download() function to initiate the download of "final_data.csv", we will use this in prediction.ipynb

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>