<a href="https://colab.research.google.com/github/sinha-diksha/Natural_Disaster_Prediction/blob/main/prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import time # Importing the time module for time-related operations
from sklearn.linear_model import LogisticRegression # Importing the LogisticRegression model from the sklearn.linear_model module
# Initializing an instance of the LogisticRegression model
# Creating an instance of the LogisticRegression model
lr=LogisticRegression()

In [ ]:
import geocoder # Importing the geocoder library for geocoding functionality
import time

Installing the geocoder library using pip3
The 'pip3' command is used to install Python packages from the PyPI repository
The 'install' command specifies that we want to install a package
'geocoder' is the name of the package we want to install

In [ ]:
!pip3 install geocoder

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 3.6 MB/s eta 0:00:00


In [ ]:
url='https://drive.google.com/file/d/1VYivEuxPgrnmASvGnbXCY_ZtjG73uNNq/view?usp=share_link' #this is the link to final_data.csv
file_id=url.split('/')[-2]
dwn_url='https://drive.google.com/uc?id=' + file_id
data = pd.read_csv(dwn_url)
print(data.head())

   Unnamed: 0    0    1      2
0           0  0.0  0.0   49.2
1           1  0.0  0.0   87.1
2           2  0.0  0.0   29.2
3           3  0.0  0.0    2.3
4           4  3.0  0.0  528.8


In [ ]:
X = np.asarray(data[['1', '2']])
X[0:5]

array([[  0. ,  49.2],
       [  0. ,  87.1],
       [  0. ,  29.2],
       [  0. ,   2.3],
       [  0. , 528.8]])

In [ ]:
y = np.asarray(data['0'])
y [0:5]

array([0., 0., 0., 0., 3.])

We are using Logistic Regression to train and test the model


Splitting the data into training and testing sets

X: The input features
y: The corresponding labels

The train_test_split function splits the X and y data into random train and test subsets
The test_size parameter determines the proportion of the data that will be allocated for testing (in this case, 0.2 or 20%)
The random_state parameter is used to ensure reproducibility of the split
The function returns four subsets: X_train, X_test, y_train, y_test


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (39513, 2) (39513,)
Test set: (9879, 2) (9879,)


#Logistic Regression


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(X_test) # The predicted labels are assigned to the variable yhat
yhat

array([0., 3., 0., ..., 3., 0., 0.])

In [ ]:
yhat_prob = LR.predict_proba(X_test) # The predicted probabilities are assigned to the variable yhat_prob
yhat_prob

array([[0.78525007, 0.07896132, 0.08984733, 0.04594128],
       [0.0304729 , 0.1482623 , 0.20486484, 0.61639997],
       [0.40020165, 0.15461027, 0.1900994 , 0.25508868],
       ...,
       [0.00526463, 0.12171572, 0.17905555, 0.6939641 ],
       [0.90926999, 0.04597822, 0.04255597, 0.00219581],
       [0.83097353, 0.06756896, 0.07515748, 0.02630002]])

In [ ]:
y_predict = LR.predict(X_test)
print('Predicted chances of flood')
print(y_predict)

Predicted chances of flood
[0. 3. 0. ... 3. 0. 0.]


In [ ]:
print('Actual chances of flood')
print(y_test)

Actual chances of flood
[0. 2. 2. ... 3. 0. 0.]


The evaluation metrics are imported from the sklearn.metrics module. The predicted probabilities for each class in the test set are obtained using the predict_proba function of the logistic regression model. These probabilities are then converted to class labels by selecting the class with the highest probability using np.argmax. The code then calculates and prints the accuracy score using accuracy_score, which compares the true labels (y_test) with the predicted labels (y_pred_proba). Additionally, the macro-averaged recall score is calculated and printed using recall_score with the average='macro' parameter.

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score, confusion_matrix

y_pred_proba = LR.predict_proba(X_test)  # Obtain predicted probabilities
y_pred_proba = np.argmax(y_pred_proba, axis=1)  # Convert probabilities to class labels

print("Accuracy score: %f" % (accuracy_score(y_test, y_pred_proba) * 100))
print("Recall score: %f" % (recall_score(y_test, y_pred_proba, average='macro') * 100))


Accuracy score: 87.427877
Recall score: 50.000000
